const BLOCKS = {
  // Languages
  java: [
    "# Java",
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    "*.nar",
    "*.zip",
    "*.tar.gz",
    "hs_err_pid*",
    ".mtj.tmp/",
  ],
  python: [
    "# Python",
    "__pycache__/",
    "*.py[cod]",
    "*$py.class",
    "*.so",
    ".Python",
    "build/",
    "dist/",
    "*.egg-info/",
    ".eggs/",
    ".venv/",
    "venv/",
    "env/",
    "ENV/",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
  ],
  node: [
    "# Node.js",
    "node_modules/",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "pnpm-debug.log*",
    ".npm",
    ".yarn/",
    "package-lock.json",
  ],
  typescript: [
    "# TypeScript",
    "*.js.map",
    "*.d.ts.map",
    "dist/",
    "out/",
    ".tsbuildinfo",
  ],
  dart: [
    "# Dart",
    ".dart_tool/",
    ".packages",
    "pubspec.lock",
    "build/",
    ".flutter-plugins",
    ".flutter-plugins-dependencies",
  ],
  go: [
    "# Go",
    "*.exe",
    "*.exe~",
    "*.dll",
    "*.so",
    "*.dylib",
    "*.test",
    "*.out",
    "vendor/",
    "go.sum",
  ],
  rust: ["# Rust", "target/", "Cargo.lock", "**/*.rs.bk"],
  csharp: [
    "# C#",
    "bin/",
    "obj/",
    "*.user",
    "*.suo",
    ".vs/",
    "*.userprefs",
    "packages/",
    "*.nupkg",
  ],

  // Frameworks
  spring: [
    "# Spring Boot",
    "target/",
    "*.jar",
    "!**/src/main/**",
    "!**/src/test/**",
    "mvnw",
    "mvnw.cmd",
    ".mvn/",
  ],
  nextjs: [
    "# Next.js",
    ".next/",
    "out/",
    ".vercel",
    "*.tsbuildinfo",
    "next-env.d.ts",
  ],
  react: [
    "# React",
    "build/",
    ".env.local",
    ".env.development.local",
    ".env.test.local",
    ".env.production.local",
  ],
  django: [
    "# Django",
    "*.log",
    "*.pot",
    "*.pyc",
    "__pycache__/",
    "local_settings.py",
    "db.sqlite3",
    "db.sqlite3-journal",
    "media/",
    "staticfiles/",
  ],
  fastapi: [
    "# FastAPI",
    "__pycache__/",
    "*.pyc",
    ".venv/",
    "venv/",
    "alembic/versions/*.pyc",
  ],
  flutter: [
    "# Flutter",
    ".dart_tool/",
    ".flutter-plugins",
    ".flutter-plugins-dependencies",
    ".pub-cache/",
    ".pub/",
    "build/",
    "*.g.dart",
    "*.freezed.dart",
  ],

  // IDEs
  idea: [
    "# IntelliJ IDEA",
    ".idea/",
    "*.iws",
    "*.iml",
    "*.ipr",
    "out/",
    ".idea_modules/",
    "atlassian-ide-plugin.xml",
  ],
  vscode: [
    "# VS Code",
    ".vscode/",
    "!.vscode/settings.json",
    "!.vscode/tasks.json",
    "!.vscode/launch.json",
    "!.vscode/extensions.json",
    "*.code-workspace",
    ".history/",
  ],
  eclipse: [
    "# Eclipse",
    ".classpath",
    ".project",
    ".settings/",
    "bin/",
    "tmp/",
    "*.tmp",
    "*.bak",
    "*.swp",
  ],
  vim: [
    "# Vim",
    "[._]*.s[a-v][a-z]",
    "[._]*.sw[a-p]",
    "Session.vim",
    ".netrwhist",
    "*~",
    "tags",
  ],

  // OS
  macos: [
    "# macOS",
    ".DS_Store",
    ".AppleDouble",
    ".LSOverride",
    "Icon",
    "._*",
    ".Spotlight-V100",
    ".Trashes",
    ".fseventsd",
  ],
  windows: [
    "# Windows",
    "Thumbs.db",
    "Thumbs.db:encryptable",
    "ehthumbs.db",
    "Desktop.ini",
    "$RECYCLE.BIN/",
    "*.lnk",
  ],
  linux: ["# Linux", "*~", ".fuse_hidden*", ".directory", ".Trash-*", ".nfs*"],

  // Extras
  docker: ["# Docker", "docker-compose.override.yml", ".docker/"],
  envs: ["# Environment variables", ".env", ".env.*", "!.env.example"],
  logs: ["# Logs", "logs/", "*.log", "log/", "*.log.*"],
  coverage: [
    "# Coverage",
    "coverage/",
    ".coverage",
    "htmlcov/",
    "*.lcov",
    ".nyc_output/",
    "coverage.xml",
    "*.cover",
  ],
};

export function generateGitignore(selections) {
  const sections = [];

  // Collect all active block keys in a logical order
  const order = [
    "java",
    "python",
    "node",
    "typescript",
    "dart",
    "go",
    "rust",
    "csharp",
    "spring",
    "nextjs",
    "react",
    "django",
    "fastapi",
    "flutter",
    "idea",
    "vscode",
    "eclipse",
    "vim",
    "macos",
    "windows",
    "linux",
    "docker",
    "envs",
    "logs",
    "coverage",
  ];

  order.forEach((key) => {
    if (selections[key] && BLOCKS[key]) {
      sections.push(BLOCKS[key].join("\n"));
    }
  });

  if (sections.length === 0) {
    return "# No options selected — pick languages, frameworks, IDEs, or extras above";
  }

  return sections.join("\n\n");
}
